credentials:
  usernames:
    usera:
      name: User A
      role: annotator
      password: $2b$12$fYW8Sy96ebCLapT4tXlvqO5XhnKRBayAxjJoVQwtpCjdRUa.Q.nd2
    userb:
      name: User B
      role: annotator
      password: $2b$12$QtxO3CBCVsCkPdu/41m7GeUFZI1Deqc9cdzAfyAJ/9yNi5z.jtwku
    userc:
      name: User C
      role: annotator
      password: $2b$12$xRxA8Ibvt4kay.r5oNXQ5e65LPELKhR1hVjjLQG5JqwebYvRhXBDe
    userd:
      name: User D
      role: annotator
      password: $2b$12$rS7.tBJBeNUUBJt23hWSFOUEsAkH1RMpDt0PSathTr55bJLDhXYXK
    usere:
      name: User E
      role: annotator
      password: $2b$12$TILeFJa.pp2JRY0H0Ko9puEFh8LLmbvz/rOVOYlEFngiVYLXJyawm
    userf:
      name: User F
      role: reviewer
      password: $2b$12$2jJIdPXnVgjGJNt/O8ILweR7LNTTfWn0Ku6bD1.FYSRWFPKe1G.BG
    userg:
      name: User G
      role: reviewer
      password: $2b$12$psEC8XNqwExo0tCMaeq8HevtjgO7iNgsZJBWoF2E.QoBXRm1xfIDG
    userh:
      name: User H
      role: reviewer
      password: $2b$12$R3KAQkCaPS8iLwoqfO0yFuzC/sjzESlhnJnjSbpfac9Hdan7Zw5RS
    useri:
      name: User I
      role: admin
      password: $2b$12$aMev8ZHSrB2I4i2YI6CG2.lkNn23NJGN6x8GHXbU/mK1dgb9j8Qp2
    userj:
      name: User J
      role: admin
      password: $2b$12$CfK4AbCBX91PirWCUG2MheLN2T./6RVdJkhPV.3uNTIfFaw1YySSi
cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name